on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest

name: PyInstaller Linux
  # You may pin to the exact commit or the version.
  # uses: JackMcKew/pyinstaller-action-linux@38639c352a36917eea765f9283bfd1092c28af7b
  uses: JackMcKew/pyinstaller-action-linux@0.1.4
  with:
    # Directory containing source code & .spec file (optional requirements.txt).
    path: # default is src
    # Specify a custom URL for PYPI
    pypi_url: # optional, default is https://pypi.python.org/
    # Specify a custom URL for PYPI Index
    pypi_index_url: # optional, default is https://pypi.python.org/simple
    # Specify a file path for .spec file
    spec: # optional, default is 
    # Specify whether to install Tkinter or not
    tkinter: # optional
          
